from .login import *
from .logout import *
from .dashboard import *
from .create_contest import *
from .contest_list import *
from .edit_contest import *
from .delete_contest import *
from .inscriptions import *
from .toggle_permanent_contests import *
from .contest_ouverture_detail import *
from .ouverture_success import *
from .export_classement_csv import *
from .export_classement_pdf import *
from .participant_detail import *
from .manage_teams import *
from .settings import *
from .frequentation import *
from .show_classement import *
from .openings_stats import *
from .opening_climbers import *
from .active_climbers import *
from .climber_progression import *
from .training_list import *
from .training_calendar import *
