name: my_climbing_list_poc
description: Initialisation POC Flutter pour la refonte de My Climbing List.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.22
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
