from django.urls import path

from .views import (
    event_home,
    event_register,
    team_access,
    staff_home,
    staff_team_list,
    staff_validate_team,
    staff_delete_team,
    staff_login,
    staff_logout,
    staff_route_list,
    staff_delete_route,
    staff_unvalidate_team,
    team_ranking,
    staff_ranking,
    staff_resend_team_link,
    staff_event_list,
    staff_event_create,
    staff_event_update,
    staff_event_delete,
    staff_phase_create,
    staff_phase_delete,
    staff_phase_update,
    staff_ranking_display,
    staff_move_route_up,
    staff_move_route_down,
    public_ranking,
    staff_toggle_route_zone,
    staff_team_update,
)

app_name = "event"

urlpatterns = [
    path("", event_home, name="home"),
    path("<slug:slug>/register/", event_register, name="register"),
    path("team/<str:token>/", team_access, name="team_access"),

    path("staff/login/", staff_login, name="staff_login"),
    path("staff/logout/", staff_logout, name="staff_logout"),
    path("staff/", staff_home, name="staff_home"),
    path("staff/<slug:slug>/teams/", staff_team_list, name="staff_team_list"),
    path("staff/<slug:slug>/routes/", staff_route_list, name="staff_route_list"),
    path("staff/team/<int:team_id>/validate/", staff_validate_team, name="staff_validate_team"),
    path("staff/team/<int:team_id>/delete/", staff_delete_team, name="staff_delete_team"),
    path("staff/route/<int:route_id>/delete/", staff_delete_route, name="staff_delete_route"),
    path("staff/team/<int:team_id>/unvalidate/", staff_unvalidate_team, name="staff_unvalidate_team"),
    path("team/<str:token>/ranking/", team_ranking, name="team_ranking"),
    path("staff/<slug:slug>/ranking/", staff_ranking, name="staff_ranking"),
    path("staff/team/<int:team_id>/resend-link/", staff_resend_team_link, name="staff_resend_team_link"),
    path("staff/events/", staff_event_list, name="staff_event_list"),
    path("staff/events/create/", staff_event_create, name="staff_event_create"),
    path("staff/events/<slug:slug>/edit/", staff_event_update, name="staff_event_update"),
    path("staff/events/<slug:slug>/delete/", staff_event_delete, name="staff_event_delete"),
    path("staff/events/<slug:slug>/phases/create/", staff_phase_create, name="staff_phase_create"),
    path("staff/phases/<int:phase_id>/delete/", staff_phase_delete, name="staff_phase_delete"),
    path("staff/phases/<int:phase_id>/edit/", staff_phase_update, name="staff_phase_update"),
    path("staff/<slug:slug>/display/", staff_ranking_display, name="staff_ranking_display"),
    path("staff/routes/<int:route_id>/up/", staff_move_route_up, name="staff_move_route_up"),
    path("staff/routes/<int:route_id>/down/", staff_move_route_down, name="staff_move_route_down"),
    path("<slug:slug>/ranking/", public_ranking, name="public_ranking"),
    path("staff/routes/<int:route_id>/toggle-zone/", staff_toggle_route_zone, name="staff_toggle_route_zone"),
    path("staff/team/<int:team_id>/edit/", staff_team_update, name="staff_team_update"),
]