from .home import *
from .salle_list import *
from .gym_properties import *
from .guidebook import *
from .confirm_session import *
from .graph import *
from .profil import *
from .logbook import *
from .settings import *
from .feedback import *
from .details import *
from .offline import *
from .projects import *
from .training import *
