name: iOS build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Où suis-je ?
        run: |
          pwd
          ls -la
          ls -la frontend/POC/my_climbing_list_poc

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Dépendances
        working-directory: frontend/POC/my_climbing_list_poc
        run: flutter pub get

      - name: Build iOS sans signature
        working-directory: frontend/POC/my_climbing_list_poc
        run: flutter build ios --release --no-codesign

      - name: Build simulateur
        working-directory: frontend/POC/my_climbing_list_poc
        run: |
          flutter build ios --simulator --debug
          cd build/ios/iphonesimulator
          zip -r Runner-simulator.zip Runner.app

      - uses: actions/upload-artifact@v4
        with:
          name: ios-simulator
          path: frontend/POC/my_climbing_list_poc/build/ios/iphonesimulator/Runner-simulator.zip
